
const audio = {
    "Genesis": [
      "https://openbible.com/audio/souer/BSB_01_Gen_001.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_002.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_003.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_004.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_005.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_006.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_007.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_008.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_009.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_010.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_011.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_012.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_013.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_014.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_015.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_016.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_017.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_018.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_019.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_020.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_021.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_022.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_023.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_024.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_025.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_026.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_027.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_028.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_029.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_030.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_031.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_032.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_033.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_034.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_035.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_036.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_037.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_038.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_039.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_040.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_041.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_042.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_043.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_044.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_045.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_046.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_047.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_048.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_049.mp3",
      "https://openbible.com/audio/souer/BSB_01_Gen_050.mp3",
    ],
  
    "Exodus": [
      "https://openbible.com/audio/souer/BSB_02_Exo_001.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_002.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_003.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_004.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_005.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_006.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_007.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_008.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_009.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_010.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_011.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_012.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_013.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_014.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_015.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_016.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_017.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_018.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_019.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_020.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_021.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_022.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_023.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_024.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_025.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_026.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_027.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_028.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_029.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_030.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_031.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_032.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_033.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_034.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_035.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_036.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_037.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_038.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_039.mp3",
      "https://openbible.com/audio/souer/BSB_02_Exo_040.mp3"
    ],
  
    "Leviticus": [
      "https://openbible.com/audio/souer/BSB_03_Lev_001.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_002.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_003.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_004.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_005.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_006.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_007.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_008.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_009.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_010.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_011.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_012.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_013.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_014.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_015.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_016.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_017.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_018.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_019.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_020.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_021.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_022.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_023.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_024.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_025.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_026.mp3",
      "https://openbible.com/audio/souer/BSB_03_Lev_027.mp3"
    ],
  
    "Numbers": [
      "https://openbible.com/audio/souer/BSB_04_Num_001.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_002.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_003.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_004.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_005.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_006.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_007.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_008.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_009.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_010.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_011.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_012.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_013.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_014.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_015.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_016.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_017.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_018.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_019.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_020.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_021.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_022.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_023.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_024.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_025.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_026.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_027.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_028.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_029.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_030.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_031.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_032.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_033.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_034.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_035.mp3",
      "https://openbible.com/audio/souer/BSB_04_Num_036.mp3"
    ],
  
    "Deuteronomy": [
      "https://openbible.com/audio/souer/BSB_05_Deu_001.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_002.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_003.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_004.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_005.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_006.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_007.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_008.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_009.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_010.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_011.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_012.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_013.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_014.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_015.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_016.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_017.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_018.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_019.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_020.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_021.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_022.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_023.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_024.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_025.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_026.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_027.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_028.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_029.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_030.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_031.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_032.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_033.mp3",
      "https://openbible.com/audio/souer/BSB_05_Deu_034.mp3"
    ],
    
    "Joshua": [
      "https://openbible.com/audio/souer/BSB_06_Jos_001.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_002.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_003.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_004.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_005.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_006.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_007.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_008.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_009.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_010.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_011.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_012.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_013.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_014.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_015.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_016.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_017.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_018.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_019.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_020.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_021.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_022.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_023.mp3",
      "https://openbible.com/audio/souer/BSB_06_Jos_024.mp3"
    ],
    
    "Judges": [
      "https://openbible.com/audio/souer/BSB_07_Jdg_001.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_002.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_003.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_004.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_005.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_006.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_007.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_008.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_009.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_010.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_011.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_012.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_013.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_014.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_015.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_016.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_017.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_018.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_019.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_020.mp3",
      "https://openbible.com/audio/souer/BSB_07_Jdg_021.mp3"
    ],
    
    "Ruth": [
      "https://openbible.com/audio/souer/BSB_08_Rut_001.mp3",
      "https://openbible.com/audio/souer/BSB_08_Rut_002.mp3",
      "https://openbible.com/audio/souer/BSB_08_Rut_003.mp3",
      "https://openbible.com/audio/souer/BSB_08_Rut_004.mp3"
    ],
    
    "1 Samuel": [
      "https://openbible.com/audio/souer/BSB_09_1Sa_001.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_002.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_003.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_004.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_005.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_006.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_007.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_008.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_009.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_010.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_011.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_012.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_013.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_014.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_015.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_016.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_017.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_018.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_019.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_020.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_021.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_022.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_023.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_024.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_025.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_026.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_027.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_028.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_029.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_030.mp3",
      "https://openbible.com/audio/souer/BSB_09_1Sa_031.mp3"
    ],
    
    "2 Samuel": [
      "https://openbible.com/audio/souer/BSB_10_2Sa_001.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_002.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_003.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_004.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_005.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_006.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_007.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_008.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_009.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_010.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_011.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_012.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_013.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_014.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_015.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_016.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_017.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_018.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_019.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_020.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_021.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_022.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_023.mp3",
      "https://openbible.com/audio/souer/BSB_10_2Sa_024.mp3"
    ],
    
    "1 Kings": [
      "https://openbible.com/audio/souer/BSB_11_1Ki_001.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_002.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_003.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_004.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_005.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_006.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_007.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_008.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_009.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_010.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_011.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_012.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_013.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_014.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_015.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_016.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_017.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_018.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_019.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_020.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_021.mp3",
      "https://openbible.com/audio/souer/BSB_11_1Ki_022.mp3"
    ],
    
    "2 Kings": [
      "https://openbible.com/audio/souer/BSB_12_2Ki_001.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_002.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_003.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_004.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_005.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_006.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_007.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_008.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_009.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_010.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_011.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_012.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_013.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_014.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_015.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_016.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_017.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_018.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_019.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_020.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_021.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_022.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_023.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_024.mp3",
      "https://openbible.com/audio/souer/BSB_12_2Ki_025.mp3"
    ],
    
    "1 Chronicles": [
      "https://openbible.com/audio/souer/BSB_13_1Ch_001.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_002.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_003.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_004.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_005.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_006.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_007.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_008.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_009.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_010.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_011.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_012.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_013.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_014.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_015.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_016.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_017.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_018.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_019.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_020.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_021.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_022.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_023.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_024.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_025.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_026.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_027.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_028.mp3",
      "https://openbible.com/audio/souer/BSB_13_1Ch_029.mp3"
    ],
    
    "2 Chronicles": [
      "https://openbible.com/audio/souer/BSB_14_2Ch_001.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_002.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_003.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_004.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_005.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_006.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_007.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_008.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_009.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_010.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_011.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_012.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_013.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_014.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_015.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_016.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_017.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_018.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_019.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_020.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_021.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_022.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_023.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_024.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_025.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_026.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_027.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_028.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_029.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_030.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_031.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_032.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_033.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_034.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_035.mp3",
      "https://openbible.com/audio/souer/BSB_14_2Ch_036.mp3"
    ],
  
    "Ezra": [
      "https://openbible.com/audio/souer/BSB_15_Ezr_001.mp3",
      "https://openbible.com/audio/souer/BSB_15_Ezr_002.mp3",
      "https://openbible.com/audio/souer/BSB_15_Ezr_003.mp3",
      "https://openbible.com/audio/souer/BSB_15_Ezr_004.mp3",
      "https://openbible.com/audio/souer/BSB_15_Ezr_005.mp3",
      "https://openbible.com/audio/souer/BSB_15_Ezr_006.mp3",
      "https://openbible.com/audio/souer/BSB_15_Ezr_007.mp3",
      "https://openbible.com/audio/souer/BSB_15_Ezr_008.mp3",
      "https://openbible.com/audio/souer/BSB_15_Ezr_009.mp3",
      "https://openbible.com/audio/souer/BSB_15_Ezr_010.mp3"
    ],
  
    "Nehemiah": [
      "https://openbible.com/audio/souer/BSB_16_Neh_001.mp3",
      "https://openbible.com/audio/souer/BSB_16_Neh_002.mp3",
      "https://openbible.com/audio/souer/BSB_16_Neh_003.mp3",
      "https://openbible.com/audio/souer/BSB_16_Neh_004.mp3",
      "https://openbible.com/audio/souer/BSB_16_Neh_005.mp3",
      "https://openbible.com/audio/souer/BSB_16_Neh_006.mp3",
      "https://openbible.com/audio/souer/BSB_16_Neh_007.mp3",
      "https://openbible.com/audio/souer/BSB_16_Neh_008.mp3",
      "https://openbible.com/audio/souer/BSB_16_Neh_009.mp3",
      "https://openbible.com/audio/souer/BSB_16_Neh_010.mp3",
      "https://openbible.com/audio/souer/BSB_16_Neh_011.mp3",
      "https://openbible.com/audio/souer/BSB_16_Neh_012.mp3",
      "https://openbible.com/audio/souer/BSB_16_Neh_013.mp3"
    ],
  
    "Esther": [
      "https://openbible.com/audio/souer/BSB_17_Est_001.mp3",
      "https://openbible.com/audio/souer/BSB_17_Est_002.mp3",
      "https://openbible.com/audio/souer/BSB_17_Est_003.mp3",
      "https://openbible.com/audio/souer/BSB_17_Est_004.mp3",
      "https://openbible.com/audio/souer/BSB_17_Est_005.mp3",
      "https://openbible.com/audio/souer/BSB_17_Est_006.mp3",
      "https://openbible.com/audio/souer/BSB_17_Est_007.mp3",
      "https://openbible.com/audio/souer/BSB_17_Est_008.mp3",
      "https://openbible.com/audio/souer/BSB_17_Est_009.mp3",
      "https://openbible.com/audio/souer/BSB_17_Est_010.mp3"
    ],
  
    "Job": [
      "https://openbible.com/audio/souer/BSB_18_Job_001.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_002.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_003.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_004.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_005.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_006.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_007.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_008.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_009.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_010.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_011.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_012.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_013.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_014.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_015.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_016.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_017.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_018.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_019.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_020.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_021.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_022.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_023.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_024.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_025.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_026.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_027.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_028.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_029.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_030.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_031.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_032.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_033.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_034.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_035.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_036.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_037.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_038.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_039.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_040.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_041.mp3",
      "https://openbible.com/audio/souer/BSB_18_Job_042.mp3"
    ],
  
    "Psalms": [
      "https://openbible.com/audio/souer/BSB_19_Psa_001.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_002.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_003.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_004.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_005.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_006.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_007.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_008.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_009.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_010.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_011.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_012.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_013.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_014.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_015.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_016.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_017.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_018.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_019.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_020.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_021.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_022.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_023.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_024.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_025.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_026.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_027.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_028.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_029.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_030.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_031.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_032.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_033.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_034.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_035.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_036.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_037.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_038.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_039.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_040.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_041.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_042.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_043.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_044.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_045.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_046.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_047.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_048.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_049.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_050.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_051.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_052.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_053.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_054.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_055.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_056.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_057.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_058.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_059.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_060.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_061.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_062.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_063.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_064.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_065.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_066.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_067.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_068.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_069.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_070.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_071.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_072.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_073.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_074.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_075.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_076.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_077.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_078.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_079.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_080.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_081.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_082.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_083.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_084.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_085.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_086.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_087.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_088.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_089.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_090.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_091.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_092.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_093.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_094.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_095.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_096.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_097.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_098.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_099.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_100.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_101.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_102.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_103.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_104.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_105.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_106.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_107.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_108.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_109.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_110.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_111.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_112.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_113.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_114.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_115.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_116.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_117.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_118.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_119.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_120.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_121.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_122.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_123.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_124.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_125.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_126.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_127.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_128.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_129.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_130.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_131.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_132.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_133.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_134.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_135.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_136.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_137.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_138.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_139.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_140.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_141.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_142.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_143.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_144.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_145.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_146.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_147.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_148.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_149.mp3",
      "https://openbible.com/audio/souer/BSB_19_Psa_150.mp3"
    ],
  
    "Proverbs": [
      "https://openbible.com/audio/souer/BSB_20_Pro_001.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_002.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_003.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_004.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_005.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_006.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_007.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_008.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_009.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_010.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_011.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_012.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_013.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_014.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_015.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_016.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_017.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_018.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_019.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_020.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_021.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_022.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_023.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_024.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_025.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_026.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_027.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_028.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_029.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_030.mp3",
      "https://openbible.com/audio/souer/BSB_20_Pro_031.mp3"
    ],
  
    "Ecclesiastes": [
      "https://openbible.com/audio/souer/BSB_21_Ecc_001.mp3",
      "https://openbible.com/audio/souer/BSB_21_Ecc_002.mp3",
      "https://openbible.com/audio/souer/BSB_21_Ecc_003.mp3",
      "https://openbible.com/audio/souer/BSB_21_Ecc_004.mp3",
      "https://openbible.com/audio/souer/BSB_21_Ecc_005.mp3",
      "https://openbible.com/audio/souer/BSB_21_Ecc_006.mp3",
      "https://openbible.com/audio/souer/BSB_21_Ecc_007.mp3",
      "https://openbible.com/audio/souer/BSB_21_Ecc_008.mp3",
      "https://openbible.com/audio/souer/BSB_21_Ecc_009.mp3",
      "https://openbible.com/audio/souer/BSB_21_Ecc_010.mp3",
      "https://openbible.com/audio/souer/BSB_21_Ecc_011.mp3",
      "https://openbible.com/audio/souer/BSB_21_Ecc_012.mp3"
    ],
  
    "Song of Solomon": [
      "https://openbible.com/audio/souer/BSB_22_Sng_001.mp3",
      "https://openbible.com/audio/souer/BSB_22_Sng_002.mp3",
      "https://openbible.com/audio/souer/BSB_22_Sng_003.mp3",
      "https://openbible.com/audio/souer/BSB_22_Sng_004.mp3",
      "https://openbible.com/audio/souer/BSB_22_Sng_005.mp3",
      "https://openbible.com/audio/souer/BSB_22_Sng_006.mp3",
      "https://openbible.com/audio/souer/BSB_22_Sng_007.mp3",
      "https://openbible.com/audio/souer/BSB_22_Sng_008.mp3"
    ],
  
    "Isaiah": [
      "https://openbible.com/audio/souer/BSB_23_Isa_001.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_002.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_003.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_004.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_005.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_006.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_007.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_008.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_009.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_010.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_011.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_012.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_013.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_014.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_015.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_016.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_017.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_018.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_019.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_020.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_021.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_022.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_023.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_024.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_025.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_026.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_027.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_028.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_029.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_030.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_031.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_032.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_033.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_034.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_035.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_036.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_037.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_038.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_039.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_040.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_041.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_042.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_043.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_044.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_045.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_046.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_047.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_048.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_049.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_050.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_051.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_052.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_053.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_054.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_055.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_056.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_057.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_058.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_059.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_060.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_061.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_062.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_063.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_064.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_065.mp3",
      "https://openbible.com/audio/souer/BSB_23_Isa_066.mp3"
    ],
  
    "Jeremiah": [
      "https://openbible.com/audio/souer/BSB_24_Jer_001.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_002.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_003.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_004.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_005.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_006.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_007.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_008.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_009.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_010.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_011.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_012.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_013.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_014.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_015.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_016.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_017.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_018.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_019.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_020.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_021.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_022.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_023.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_024.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_025.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_026.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_027.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_028.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_029.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_030.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_031.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_032.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_033.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_034.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_035.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_036.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_037.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_038.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_039.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_040.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_041.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_042.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_043.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_044.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_045.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_046.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_047.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_048.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_049.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_050.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_051.mp3",
      "https://openbible.com/audio/souer/BSB_24_Jer_052.mp3"
    ],
  
    "Lamentations": [
      "https://openbible.com/audio/souer/BSB_25_Lam_001.mp3",
      "https://openbible.com/audio/souer/BSB_25_Lam_002.mp3",
      "https://openbible.com/audio/souer/BSB_25_Lam_003.mp3",
      "https://openbible.com/audio/souer/BSB_25_Lam_004.mp3",
      "https://openbible.com/audio/souer/BSB_25_Lam_005.mp3"
    ],
  
    "Ezekiel": [
      "https://openbible.com/audio/souer/BSB_26_Ezk_001.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_002.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_003.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_004.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_005.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_006.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_007.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_008.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_009.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_010.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_011.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_012.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_013.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_014.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_015.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_016.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_017.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_018.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_019.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_020.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_021.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_022.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_023.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_024.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_025.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_026.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_027.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_028.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_029.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_030.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_031.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_032.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_033.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_034.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_035.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_036.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_037.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_038.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_039.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_040.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_041.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_042.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_043.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_044.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_045.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_046.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_047.mp3",
      "https://openbible.com/audio/souer/BSB_26_Ezk_048.mp3"
    ],
  
    "Daniel": [
      "https://openbible.com/audio/souer/BSB_27_Dan_001.mp3",
      "https://openbible.com/audio/souer/BSB_27_Dan_002.mp3",
      "https://openbible.com/audio/souer/BSB_27_Dan_003.mp3",
      "https://openbible.com/audio/souer/BSB_27_Dan_004.mp3",
      "https://openbible.com/audio/souer/BSB_27_Dan_005.mp3",
      "https://openbible.com/audio/souer/BSB_27_Dan_006.mp3",
      "https://openbible.com/audio/souer/BSB_27_Dan_007.mp3",
      "https://openbible.com/audio/souer/BSB_27_Dan_008.mp3",
      "https://openbible.com/audio/souer/BSB_27_Dan_009.mp3",
      "https://openbible.com/audio/souer/BSB_27_Dan_010.mp3",
      "https://openbible.com/audio/souer/BSB_27_Dan_011.mp3",
      "https://openbible.com/audio/souer/BSB_27_Dan_012.mp3"
    ],
  
    "Hosea": [
      "https://openbible.com/audio/souer/BSB_28_Hos_001.mp3",
      "https://openbible.com/audio/souer/BSB_28_Hos_002.mp3",
      "https://openbible.com/audio/souer/BSB_28_Hos_003.mp3",
      "https://openbible.com/audio/souer/BSB_28_Hos_004.mp3",
      "https://openbible.com/audio/souer/BSB_28_Hos_005.mp3",
      "https://openbible.com/audio/souer/BSB_28_Hos_006.mp3",
      "https://openbible.com/audio/souer/BSB_28_Hos_007.mp3",
      "https://openbible.com/audio/souer/BSB_28_Hos_008.mp3",
      "https://openbible.com/audio/souer/BSB_28_Hos_009.mp3",
      "https://openbible.com/audio/souer/BSB_28_Hos_010.mp3",
      "https://openbible.com/audio/souer/BSB_28_Hos_011.mp3",
      "https://openbible.com/audio/souer/BSB_28_Hos_012.mp3",
      "https://openbible.com/audio/souer/BSB_28_Hos_013.mp3",
      "https://openbible.com/audio/souer/BSB_28_Hos_014.mp3"
    ],
  
    "Joel": [
      "https://openbible.com/audio/souer/BSB_29_Jol_001.mp3",
      "https://openbible.com/audio/souer/BSB_29_Jol_002.mp3",
      "https://openbible.com/audio/souer/BSB_29_Jol_003.mp3"
    ],
  
    "Amos": [
      "https://openbible.com/audio/souer/BSB_30_Amo_001.mp3",
      "https://openbible.com/audio/souer/BSB_30_Amo_002.mp3",
      "https://openbible.com/audio/souer/BSB_30_Amo_003.mp3",
      "https://openbible.com/audio/souer/BSB_30_Amo_004.mp3",
      "https://openbible.com/audio/souer/BSB_30_Amo_005.mp3",
      "https://openbible.com/audio/souer/BSB_30_Amo_006.mp3",
      "https://openbible.com/audio/souer/BSB_30_Amo_007.mp3",
      "https://openbible.com/audio/souer/BSB_30_Amo_008.mp3",
      "https://openbible.com/audio/souer/BSB_30_Amo_009.mp3"
    ],
  
    "Obadiah": [
      "https://openbible.com/audio/souer/BSB_31_Oba_001.mp3"
    ],
  
    "Jonah": [
      "https://openbible.com/audio/souer/BSB_32_Jon_001.mp3",
      "https://openbible.com/audio/souer/BSB_32_Jon_002.mp3",
      "https://openbible.com/audio/souer/BSB_32_Jon_003.mp3",
      "https://openbible.com/audio/souer/BSB_32_Jon_004.mp3"
    ],
  
    "Micah": [
      "https://openbible.com/audio/souer/BSB_33_Mic_001.mp3",
      "https://openbible.com/audio/souer/BSB_33_Mic_002.mp3",
      "https://openbible.com/audio/souer/BSB_33_Mic_003.mp3",
      "https://openbible.com/audio/souer/BSB_33_Mic_004.mp3",
      "https://openbible.com/audio/souer/BSB_33_Mic_005.mp3",
      "https://openbible.com/audio/souer/BSB_33_Mic_006.mp3",
      "https://openbible.com/audio/souer/BSB_33_Mic_007.mp3"
    ],
  
    "Nahum": [
      "https://openbible.com/audio/souer/BSB_34_Nam_001.mp3",
      "https://openbible.com/audio/souer/BSB_34_Nam_002.mp3",
      "https://openbible.com/audio/souer/BSB_34_Nam_003.mp3"
    ],
  
    "Habakkuk": [
      "https://openbible.com/audio/souer/BSB_35_Hab_001.mp3",
      "https://openbible.com/audio/souer/BSB_35_Hab_002.mp3",
      "https://openbible.com/audio/souer/BSB_35_Hab_003.mp3"
    ],
  
    "Zephaniah": [
      "https://openbible.com/audio/souer/BSB_36_Zep_001.mp3",
      "https://openbible.com/audio/souer/BSB_36_Zep_002.mp3",
      "https://openbible.com/audio/souer/BSB_36_Zep_003.mp3"
    ],
  
    "Haggai": [
      "https://openbible.com/audio/souer/BSB_37_Hag_001.mp3",
      "https://openbible.com/audio/souer/BSB_37_Hag_002.mp3"
    ],
  
    "Zechariah": [
      "https://openbible.com/audio/souer/BSB_38_Zec_001.mp3",
      "https://openbible.com/audio/souer/BSB_38_Zec_002.mp3",
      "https://openbible.com/audio/souer/BSB_38_Zec_003.mp3",
      "https://openbible.com/audio/souer/BSB_38_Zec_004.mp3",
      "https://openbible.com/audio/souer/BSB_38_Zec_005.mp3",
      "https://openbible.com/audio/souer/BSB_38_Zec_006.mp3",
      "https://openbible.com/audio/souer/BSB_38_Zec_007.mp3",
      "https://openbible.com/audio/souer/BSB_38_Zec_008.mp3",
      "https://openbible.com/audio/souer/BSB_38_Zec_009.mp3",
      "https://openbible.com/audio/souer/BSB_38_Zec_010.mp3",
      "https://openbible.com/audio/souer/BSB_38_Zec_011.mp3",
      "https://openbible.com/audio/souer/BSB_38_Zec_012.mp3",
      "https://openbible.com/audio/souer/BSB_38_Zec_013.mp3",
      "https://openbible.com/audio/souer/BSB_38_Zec_014.mp3"
    ],
  
    "Malachi": [
      "https://openbible.com/audio/souer/BSB_39_Mal_001.mp3",
      "https://openbible.com/audio/souer/BSB_39_Mal_002.mp3",
      "https://openbible.com/audio/souer/BSB_39_Mal_003.mp3",
      "https://openbible.com/audio/souer/BSB_39_Mal_004.mp3"
    ],
  
    "Matthew": [
      "https://openbible.com/audio/souer/BSB_40_Mat_001.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_002.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_003.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_004.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_005.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_006.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_007.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_008.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_009.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_010.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_011.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_012.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_013.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_014.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_015.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_016.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_017.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_018.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_019.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_020.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_021.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_022.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_023.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_024.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_025.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_026.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_027.mp3",
      "https://openbible.com/audio/souer/BSB_40_Mat_028.mp3"
    ],
  
    "Mark": [
      "https://openbible.com/audio/souer/BSB_41_Mrk_001.mp3",
      "https://openbible.com/audio/souer/BSB_41_Mrk_002.mp3",
      "https://openbible.com/audio/souer/BSB_41_Mrk_003.mp3",
      "https://openbible.com/audio/souer/BSB_41_Mrk_004.mp3",
      "https://openbible.com/audio/souer/BSB_41_Mrk_005.mp3",
      "https://openbible.com/audio/souer/BSB_41_Mrk_006.mp3",
      "https://openbible.com/audio/souer/BSB_41_Mrk_007.mp3",
      "https://openbible.com/audio/souer/BSB_41_Mrk_008.mp3",
      "https://openbible.com/audio/souer/BSB_41_Mrk_009.mp3",
      "https://openbible.com/audio/souer/BSB_41_Mrk_010.mp3",
      "https://openbible.com/audio/souer/BSB_41_Mrk_011.mp3",
      "https://openbible.com/audio/souer/BSB_41_Mrk_012.mp3",
      "https://openbible.com/audio/souer/BSB_41_Mrk_013.mp3",
      "https://openbible.com/audio/souer/BSB_41_Mrk_014.mp3",
      "https://openbible.com/audio/souer/BSB_41_Mrk_015.mp3",
      "https://openbible.com/audio/souer/BSB_41_Mrk_016.mp3"
    ],
  
    "Luke": [
      "https://openbible.com/audio/souer/BSB_42_Luk_001.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_002.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_003.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_004.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_005.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_006.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_007.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_008.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_009.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_010.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_011.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_012.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_013.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_014.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_015.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_016.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_017.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_018.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_019.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_020.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_021.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_022.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_023.mp3",
      "https://openbible.com/audio/souer/BSB_42_Luk_024.mp3"
    ],
  
    "John": [
      "https://openbible.com/audio/souer/BSB_43_Jhn_001.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_002.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_003.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_004.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_005.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_006.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_007.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_008.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_009.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_010.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_011.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_012.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_013.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_014.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_015.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_016.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_017.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_018.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_019.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_020.mp3",
      "https://openbible.com/audio/souer/BSB_43_Jhn_021.mp3"
    ],
  
    "Acts": [
      "https://openbible.com/audio/souer/BSB_44_Act_001.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_002.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_003.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_004.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_005.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_006.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_007.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_008.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_009.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_010.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_011.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_012.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_013.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_014.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_015.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_016.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_017.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_018.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_019.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_020.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_021.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_022.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_023.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_024.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_025.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_026.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_027.mp3",
      "https://openbible.com/audio/souer/BSB_44_Act_028.mp3"
    ],
  
    "Romans": [
      "https://openbible.com/audio/souer/BSB_45_Rom_001.mp3",
      "https://openbible.com/audio/souer/BSB_45_Rom_002.mp3",
      "https://openbible.com/audio/souer/BSB_45_Rom_003.mp3",
      "https://openbible.com/audio/souer/BSB_45_Rom_004.mp3",
      "https://openbible.com/audio/souer/BSB_45_Rom_005.mp3",
      "https://openbible.com/audio/souer/BSB_45_Rom_006.mp3",
      "https://openbible.com/audio/souer/BSB_45_Rom_007.mp3",
      "https://openbible.com/audio/souer/BSB_45_Rom_008.mp3",
      "https://openbible.com/audio/souer/BSB_45_Rom_009.mp3",
      "https://openbible.com/audio/souer/BSB_45_Rom_010.mp3",
      "https://openbible.com/audio/souer/BSB_45_Rom_011.mp3",
      "https://openbible.com/audio/souer/BSB_45_Rom_012.mp3",
      "https://openbible.com/audio/souer/BSB_45_Rom_013.mp3",
      "https://openbible.com/audio/souer/BSB_45_Rom_014.mp3",
      "https://openbible.com/audio/souer/BSB_45_Rom_015.mp3",
      "https://openbible.com/audio/souer/BSB_45_Rom_016.mp3"
    ],
  
    "1 Corinthians": [
      "https://openbible.com/audio/souer/BSB_46_1Co_001.mp3",
      "https://openbible.com/audio/souer/BSB_46_1Co_002.mp3",
      "https://openbible.com/audio/souer/BSB_46_1Co_003.mp3",
      "https://openbible.com/audio/souer/BSB_46_1Co_004.mp3",
      "https://openbible.com/audio/souer/BSB_46_1Co_005.mp3",
      "https://openbible.com/audio/souer/BSB_46_1Co_006.mp3",
      "https://openbible.com/audio/souer/BSB_46_1Co_007.mp3",
      "https://openbible.com/audio/souer/BSB_46_1Co_008.mp3",
      "https://openbible.com/audio/souer/BSB_46_1Co_009.mp3",
      "https://openbible.com/audio/souer/BSB_46_1Co_010.mp3",
      "https://openbible.com/audio/souer/BSB_46_1Co_011.mp3",
      "https://openbible.com/audio/souer/BSB_46_1Co_012.mp3",
      "https://openbible.com/audio/souer/BSB_46_1Co_013.mp3",
      "https://openbible.com/audio/souer/BSB_46_1Co_014.mp3",
      "https://openbible.com/audio/souer/BSB_46_1Co_015.mp3",
      "https://openbible.com/audio/souer/BSB_46_1Co_016.mp3"  
    ],
  
    "2 Corinthians": [
      "https://openbible.com/audio/souer/BSB_47_2Co_001.mp3",
      "https://openbible.com/audio/souer/BSB_47_2Co_002.mp3",
      "https://openbible.com/audio/souer/BSB_47_2Co_003.mp3",
      "https://openbible.com/audio/souer/BSB_47_2Co_004.mp3",
      "https://openbible.com/audio/souer/BSB_47_2Co_005.mp3",
      "https://openbible.com/audio/souer/BSB_47_2Co_006.mp3",
      "https://openbible.com/audio/souer/BSB_47_2Co_007.mp3",
      "https://openbible.com/audio/souer/BSB_47_2Co_008.mp3",
      "https://openbible.com/audio/souer/BSB_47_2Co_009.mp3",
      "https://openbible.com/audio/souer/BSB_47_2Co_010.mp3",
      "https://openbible.com/audio/souer/BSB_47_2Co_011.mp3",
      "https://openbible.com/audio/souer/BSB_47_2Co_012.mp3",
      "https://openbible.com/audio/souer/BSB_47_2Co_013.mp3"
    ],
  
    "Galatians": [
      "https://openbible.com/audio/souer/BSB_48_Gal_001.mp3",
      "https://openbible.com/audio/souer/BSB_48_Gal_002.mp3",
      "https://openbible.com/audio/souer/BSB_48_Gal_003.mp3",
      "https://openbible.com/audio/souer/BSB_48_Gal_004.mp3",
      "https://openbible.com/audio/souer/BSB_48_Gal_005.mp3",
      "https://openbible.com/audio/souer/BSB_48_Gal_006.mp3"
    ],
  
    "Ephesians": [
      "https://openbible.com/audio/souer/BSB_49_Eph_001.mp3",
      "https://openbible.com/audio/souer/BSB_49_Eph_002.mp3",
      "https://openbible.com/audio/souer/BSB_49_Eph_003.mp3",
      "https://openbible.com/audio/souer/BSB_49_Eph_004.mp3",
      "https://openbible.com/audio/souer/BSB_49_Eph_005.mp3",
      "https://openbible.com/audio/souer/BSB_49_Eph_006.mp3"
    ],
  
    "Philippians": [
      "https://openbible.com/audio/souer/BSB_50_Php_001.mp3",
      "https://openbible.com/audio/souer/BSB_50_Php_002.mp3",
      "https://openbible.com/audio/souer/BSB_50_Php_003.mp3",
      "https://openbible.com/audio/souer/BSB_50_Php_004.mp3"
    ],
  
    "Colossians": [
      "https://openbible.com/audio/souer/BSB_51_Col_001.mp3",
      "https://openbible.com/audio/souer/BSB_51_Col_002.mp3",
      "https://openbible.com/audio/souer/BSB_51_Col_003.mp3",
      "https://openbible.com/audio/souer/BSB_51_Col_004.mp3"
    ],
  
    "1 Thessalonians": [
      "https://openbible.com/audio/souer/BSB_52_1Th_001.mp3",
      "https://openbible.com/audio/souer/BSB_52_1Th_002.mp3",
      "https://openbible.com/audio/souer/BSB_52_1Th_003.mp3",
      "https://openbible.com/audio/souer/BSB_52_1Th_004.mp3",
      "https://openbible.com/audio/souer/BSB_52_1Th_005.mp3"
    ],
  
    "2 Thessalonians": [
      "https://openbible.com/audio/souer/BSB_53_2Th_001.mp3",
      "https://openbible.com/audio/souer/BSB_53_2Th_002.mp3",
      "https://openbible.com/audio/souer/BSB_53_2Th_003.mp3"
    ],
  
    "1 Timothy": [
      "https://openbible.com/audio/souer/BSB_54_1Ti_001.mp3",
      "https://openbible.com/audio/souer/BSB_54_1Ti_002.mp3",
      "https://openbible.com/audio/souer/BSB_54_1Ti_003.mp3",
      "https://openbible.com/audio/souer/BSB_54_1Ti_004.mp3",
      "https://openbible.com/audio/souer/BSB_54_1Ti_005.mp3",
      "https://openbible.com/audio/souer/BSB_54_1Ti_006.mp3"
    ],
  
    "2 Timothy": [
      "https://openbible.com/audio/souer/BSB_55_2Ti_001.mp3",
      "https://openbible.com/audio/souer/BSB_55_2Ti_002.mp3",
      "https://openbible.com/audio/souer/BSB_55_2Ti_003.mp3",
      "https://openbible.com/audio/souer/BSB_55_2Ti_004.mp3"
    ],
  
    "Titus": [
      "https://openbible.com/audio/souer/BSB_56_Tts_001.mp3",
      "https://openbible.com/audio/souer/BSB_56_Tts_002.mp3",
      "https://openbible.com/audio/souer/BSB_56_Tts_003.mp3"
    ],
  
    "Philemon": [
      "https://openbible.com/audio/souer/BSB_57_Phm_001.mp3"
    ],
  
    "Hebrews": [
      "https://openbible.com/audio/souer/BSB_58_Heb_001.mp3",
      "https://openbible.com/audio/souer/BSB_58_Heb_002.mp3",
      "https://openbible.com/audio/souer/BSB_58_Heb_003.mp3",
      "https://openbible.com/audio/souer/BSB_58_Heb_004.mp3",
      "https://openbible.com/audio/souer/BSB_58_Heb_005.mp3",
      "https://openbible.com/audio/souer/BSB_58_Heb_006.mp3",
      "https://openbible.com/audio/souer/BSB_58_Heb_007.mp3",
      "https://openbible.com/audio/souer/BSB_58_Heb_008.mp3",
      "https://openbible.com/audio/souer/BSB_58_Heb_009.mp3",
      "https://openbible.com/audio/souer/BSB_58_Heb_010.mp3",
      "https://openbible.com/audio/souer/BSB_58_Heb_011.mp3",
      "https://openbible.com/audio/souer/BSB_58_Heb_012.mp3",
      "https://openbible.com/audio/souer/BSB_58_Heb_013.mp3"
    ],
  
    "James": [
      "https://openbible.com/audio/souer/BSB_59_Jas_001.mp3",
      "https://openbible.com/audio/souer/BSB_59_Jas_002.mp3",
      "https://openbible.com/audio/souer/BSB_59_Jas_003.mp3",
      "https://openbible.com/audio/souer/BSB_59_Jas_004.mp3",
      "https://openbible.com/audio/souer/BSB_59_Jas_005.mp3"
    ],
  
    "1 Peter": [
      "https://openbible.com/audio/souer/BSB_60_1Pe_001.mp3",
      "https://openbible.com/audio/souer/BSB_60_1Pe_002.mp3",
      "https://openbible.com/audio/souer/BSB_60_1Pe_003.mp3",
      "https://openbible.com/audio/souer/BSB_60_1Pe_004.mp3",
      "https://openbible.com/audio/souer/BSB_60_1Pe_005.mp3"
    ],
  
    "2 Peter": [
      "https://openbible.com/audio/souer/BSB_61_2Pe_001.mp3",
      "https://openbible.com/audio/souer/BSB_61_2Pe_002.mp3",
      "https://openbible.com/audio/souer/BSB_61_2Pe_003.mp3"
    ],
  
    "1 John": [
      "https://openbible.com/audio/souer/BSB_62_1Jn_001.mp3",
      "https://openbible.com/audio/souer/BSB_62_1Jn_002.mp3",
      "https://openbible.com/audio/souer/BSB_62_1Jn_003.mp3",
      "https://openbible.com/audio/souer/BSB_62_1Jn_004.mp3",
      "https://openbible.com/audio/souer/BSB_62_1Jn_005.mp3"
    ],
  
    "2 John": [
      "https://openbible.com/audio/souer/BSB_63_2Jn_001.mp3"
    ],
  
    "3 John": [
      "https://openbible.com/audio/souer/BSB_64_3Jn_001.mp3"
    ],
  
    "Jude": [
      "https://openbible.com/audio/souer/BSB_65_Jud_001.mp3"
    ],
  
    "Revelation": [
      "https://openbible.com/audio/souer/BSB_66_Rev_001.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_002.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_003.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_004.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_005.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_006.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_007.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_008.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_009.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_010.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_011.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_012.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_013.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_014.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_015.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_016.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_017.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_018.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_019.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_020.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_021.mp3",
      "https://openbible.com/audio/souer/BSB_66_Rev_022.mp3"
    ]
  };
  
  const booksList = [
    "Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy", "Joshua", "Judges", "Ruth", "1 Samuel", "2 Samuel", "1 Kings",
    "2 Kings", "1 Chronicles", "2 Chronicles", "Ezra", "Nehemiah", "Esther", "Job", "Psalms", "Proverbs", "Ecclesiastes", "Song of Solomon",
    "Isaiah", "Jeremiah", "Lamentations", "Ezekiel", "Daniel", "Hosea", "Joel", "Amos", "Obadiah", "Jonah", "Micah", "Nahum", "Habakkuk",
     "Zephaniah", "Haggai", "Zechariah", "Malachi", "Matthew", "Mark", "Luke", "John", "Acts", "Romans", "1 Corinthians", "2 Corinthians", 
     "Galatians", "Ephesians", "Philippians", "Colossians", "1 Thessalonians", "2 Thessalonians", "1 Timothy", "2 Timothy", "Titus", 
     "Philemon", "Hebrews", "James", "1 Peter", "2 Peter", "1 John", "2 John", "3 John", "Jude", "Revelation"
  ];
  
  const chaptersList = [
    50, 40, 27, 36, 34, 24, 21, 4, 31, 24, 22, 25, 29, 36, 10, 13, 10, 42, 150, 31, 12, 8, 66, 52, 5, 48,
    12, 14, 3, 9, 1, 4, 7, 3, 3, 3, 2, 14, 4, 28, 16, 24, 21, 28, 16, 16, 13, 6, 6, 4, 4, 5, 3, 6, 4, 3,
    1, 13, 5, 5, 3, 5, 1, 1, 1, 22
  ];
  
  const lofi = [
    {
      file: "https://github.com/ryancornett/lofiaudiofiles/raw/main/good-night-160166.mp3",
      artist: "FASSounds",
      title: "Good Night",
      source: "https://pixabay.com/music/beats-good-night-160166/"
    },
    {
      file: "https://github.com/ryancornett/lofiaudiofiles/raw/main/ciudades-lo-fi-music-produced-by-rame-syncopation-station-198728.mp3",
      artist: "SyncopationStation",
      title: "Ciudades",
      source: "https://pixabay.com/music/beats-ciudades-lo-fi-music-produced-by-rame-syncopation-station-198728/"
    },
    {
      file: "https://github.com/ryancornett/lofiaudiofiles/raw/main/chill-lofi-song-8444.mp3",
      artist: "virtuosound",
      title: "Chill Lofi Song",
      source: "https://pixabay.com/music/beats-chill-lofi-song-8444/"
    },
    {
      file: "https://github.com/ryancornett/lofiaudiofiles/raw/main/close-study-relax-chillhop-calm-study-lofi-123089.mp3",
      artist: "SoulProdMusic",
      title: "Close / Calm Study",
      source: "https://pixabay.com/music/beats-close-study-relax-chillhop-calm-study-lofi-123089/"
    },
    {
      file: "https://github.com/ryancornett/lofiaudiofiles/raw/main/close-study-relax-chillhop-calm-study-lofi-123089.mp3",
      artist: "MYAUDIOVISION",
      title: "Coverless Book",
      source: "https://pixabay.com/music/beats-coverless-book-lofi-186307/"
    },
  
  ];
  
  export { audio, booksList, chaptersList, lofi };
  